[rule]
author = ["Kaiber Yonnij"]
description = "This alert looks for both specific files and file extensions written to a file path containing WIndows\\Temp\\"
from = "now-6m"
name = "suspicious_file_written_to_temp_directory"
risk_score = 67
severity = "medium"
type = "query"

query = '''
event.action : (creation or overwrite) and process.name : *powershell.exe* and file.path : *Windows\\Temp\\* and file.name : (History or *.txt)
'''

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1082"
name = "System Information Discovery"
reference = "https://attack.mitre.org/techniques/T1082/"
[[rule.threat.technique]]
id = "T1217"
name = "Browser Information Discovery"
reference = "https://attack.mitre.org/techniques/T1217/"

[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"
