[metadata]
creation_date = "2023/12/21"

[rule]
author = ["Kaiber Yonnij"]
description = "This alert looks for .ps1 files added to autorun on bootup locations in the Windows Registry."
from = "now-6m"
name = "suspicious_file_added_to_registry"
risk_score = 47
severity = "medium"
type = "query"
rule_id = "00000000-0000-0000-0000-000000000005"

query = '''
"event.dataset" : "windows.sysmon_operational" and "registry.key" : "*CurrentVersion\\Run*" and "event.action" : "RegistryEvent*Value*Set*" and "registry.path" : "*Microsoft\\Windows\\CurrentVersion\\Run*" and "registry.data.strings" : "*.ps1*"
'''

[[rule.threat]] 
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1547"
name = "Boot or Logon Autostart Execution"
reference = "https://attack.mitre.org/techniques/T1547/"
[[rule.threat.technique.subtechnique]]
id = "T1547.001"
name = "Registry Run Keys / Startup Folder"
reference = "https://attack.mitre.org/techniques/T1547/001/"

[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"
