[rule]
author = ["Kaiber Yonnij"]
description = "Using sysmon data, triggers on downloaded bat files from the internet via powershell."
from = "now-6m"
name = "new_alert"
risk_score = 1
severity = "medium"
type = "query"
rule_id = "00000000-0000-0000-0000-000000000002"

query = '''
event.dataset : "windows.sysmon_operational" and process.parent.command_line: *Invoke-WebRequest* and process.parent.name: powershell.exe and process.command_line: *bat*
'''

[[rule.threat]] 
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[rule.threat.technique.subtechnique]]
id = "T1059.003"
name = "Windows Command Shell"
reference = "https://attack.mitre.org/techniques/T1059/003/"

[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
