[rule]
author = ["Kaiber Yonnij"]
description = "Checks my zeek.http data set which includes all http traffic within my homelab and looks for url extensions that have bat in them, and ports that do not equal 80."
from = "now-6m"
name = "malicious_file_over_unknown_ports"
risk_score = 50
severity = "medium"
type = "query"

query = '''
event.dataset: "zeek.http" and  url.extension: bat and not destination.port: 80
'''

[[rule.threat]] 
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[rule.threat.technique.subtechnique]]
id = "T1059.003"
name = "Windows Command Shell"
reference = "https://attack.mitre.org/techniques/T1059/003/"

[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
