[rule]
author = ["Kaiber Yonnij"]
description = "Triggers when more the 1000 queries to a web server have been obeserves in a 5 min window."
from = "now-6m"
name = "excessive_web_traffic"
risk_score = 19
severity = "low"
type = "threshold"
rule_id = "00000000-0000-0000-0000-000000000008"

query = '''
event.dataset : "zeek.http" 
'''
[rule.threshold]
field = ["source.ip"]
value = 1000

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"

[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"