name: TOML/MITRE Validation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - run:
          python development/validation.py
          python development/mitre.py 

